services:
  accounts-java:
    build: .
    container_name: BankAPI
    ports:
      - "8070:8080"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_JSON: '{
        "jwt.secret": "$JWT_SECRET",
        "server.domain": "$SERVER_DOMAIN",
        "server.port": $SERVER_PORT,
        "cors.allowedOrigins": "$CORS_ALLOWED_ORIGINS",
        "encryption.password": "$ENCRYPTION_PASSWORD",
        "encryption.salt": "$ENCRYPTION_SALT",
        "jpa.properties.hibernate.show_sql": false,
        "spring.datasource.url": "jdbc:postgresql://BankAPI-db:5432/$POSTGRES_DB",
        "spring.datasource.username": "$POSTGRES_USER",
        "spring.datasource.password": "$POSTGRES_PASSWORD"
      }'
    env_file: ".env"

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
      - 'POSTGRES_USER=$POSTGRES_USER'
    ports:
      - ':5432'
    container_name: BankAPI-db
    volumes:
      - bankapi-volume:/var/lib/postgresql/data
    env_file: ".env"

volumes:
  bankapi-volume: