services:
  accounts-java:
    build: .
    container_name: BankAPI
    ports:
      - "8070:8070"
    depends_on:
      - accounts-mongo
    environment:
      SPRING_APPLICATION_JSON: '{
        "security.require-ssl": $REQUIRE_SSL,
        "server.ssl.key-store": "$SERVER_SSL_KEY_STORE",
        "server.ssl.key-store-password": "$SERVER_SSL_KEY_STORE_PASSWORD",
        "server.ssl.keyStoreType": "$SERVER_SSL_KEY_STORE_TYPE",
        "server.ssl.keyAlias": "$SERVER_SSL_KEY_ALIAS",
        "server.domain": "$SERVER_DOMAIN"
        "cors.allowedOrigins": "$CORS_ALLOWED_ORIGINS",
        "encryption.password": "$ENCRYPTION_PASSWORD",
        "encryption.salt": "$ENCRYPTION_SALT",
        "jpa.properties.hibernate.show_sql": false,
        "spring.datasource.url": "jdbc:postgresql://BankAPI-db:5432/$POSTGRES_DB",
        "spring.datasource.username": "$POSTGRES_USER",
        "spring.datasource.password": "$POSTGRES_PASSWORD"
      }'
    env_file: ".env"

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
      - 'POSTGRES_USER=$POSTGRES_USER'
    ports:
      - ':5432'
    container_name: BankAPI-db
    volumes:
      - BankAPI-data:/var/lib/postgresql/data
    env_file: ".env"

volumes:
  BankAPI: