spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  liquibase:
    change-log: classpath:db/migration/master.yaml
#    enabled: false

jwt:
  secret: SECRET
  issuer: localhost
  days_until_expiration: 1

encryption:
  password: "password"
  salt: "saltsaltsaltsalt"

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger
    operations-sorter: alpha